name: Update GitHub Profile Status

on:
  schedule:
    - cron: '0 * * * *'  # Run every hour, you can modify the cron expression to suit your needs
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  update-status:
    runs-on: ubuntu-latest  # Use an Ubuntu environment to run the script

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3  # Check out the repository during the action

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Set the Python version you'll be using

    - name: Install dependencies
      run: pip install requests  # Install the requests library needed for making HTTP requests

    - name: Update the profile status
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}  # Get the token from the secrets in GitHub
      run: python update_status.py  # Run the Python script that updates the status
