name: Update GitHub Profile Status

# Triggers the workflow on schedule (every 15 minutes) or manually
on:
  schedule:
    - cron: '*/15 * * * *'  # Run every 15 minutes (adjust cron expression as needed)
  workflow_dispatch:  # Allows manual triggering of the workflow as well

jobs:
  update_status:
    runs-on: ubuntu-latest  # Specifies the environment to run the job

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Checks out the repository to access files

      - name: Set up Python
        uses: actions/setup-python@v4  # Sets up Python environment
        with:
          python-version: '3.x'  # Set Python version to 3.x (ensure compatibility)

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  # Upgrades pip to latest version
          pip install requests  # Installs the required Python libraries (requests)

      - name: Update status on GitHub
        run: |
          python update_status.py  # Runs the Python script to update GitHub profile status
          
      - name: Push status change
        run: echo "GitHub status updated successfully!"  # Prints success message after status is updated
