name: Update GitHub Profile Quote

on:
  schedule:
    - cron: '*/15 * * * *'  # Run every 15 minutes
  workflow_dispatch:  # Allows manual triggering as well

jobs:
  update_quote:
    runs-on: ubuntu-latest  # Specifies the environment to run the job

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Checks out the repository to access files

      - name: Set up Python
        uses: actions/setup-python@v4  # Sets up the Python environment
        with:
          python-version: '3.x'  # Specifies the Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  # Upgrades pip
          pip install requests  # Installs any required dependencies (optional)

      - name: Update quote in README
        run: |
          python Quote/update_quote.py  # Runs the Python script from the Quote folder

      - name: Commit updated README
        run: |
          git config --global user.name "GitHub Actions"  # Set up git config
          git config --global user.email "actions@github.com"  # Set up git config
          git add README.md  # Stages the README file for commit
          git commit -m "Update quote in README"  # Commit the changes
          git push  # Push the changes to the repository
